apiVersion: apps/v1
kind: Deployment
metadata:
  name: finacplus-deployment
  namespace: finacplus
  labels:
    app: finacplus-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: finacplus-app
  template:
    metadata:
      labels:
        app: finacplus-app
    spec:
      containers:
      - name: finacplus-con
        image: uj5ghare/finacplus:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1