apiVersion: v1
kind: Service
metadata:
  name: finacplus-svc
  namespace: finacplus
spec:
  selector:
    app: finacplus-app
  ports:
  - port: 80
    targetPort: 5000
  # nodePort: 30007
  # type: NodePort